const movies = [
    {
        title: "Deadpool",
        year: 2016,
        director: "Tim Miller",
        duration: "1h 48min",
        actors: ["Ryan Reynolds", "Morena Baccarin", "Ed Skrein"],
    },
    {
        title: "The Shawshank Redemption",
        year: 1994,
        director: "Frank Darabont",
        duration: "2h 22min",
        actors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    },
    {
        title: "The Godfather",
        year: 1972,
        director: "Francis Ford Coppola",
        duration: "2h 55min",
        actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    },
    {
        title: "The Dark Knight",
        year: 2008,
        director: "Christopher Nolan",
        duration: "2h 32min",
        actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    },
    {
        title: "Pulp Fiction",
        year: 1994,
        director: "Quentin Tarantino",
        duration: "2h 34min",
        actors: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
    },
    {
        title: "Fight Club",
        year: 1999,
        director: "David Fincher",
        duration: "2h 19min",
        actors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    },
    {
        title: "Forrest Gump",
        year: 1994,
        director: "Robert Zemeckis",
        duration: "2h 22min",
        actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    },
    {
        title: "Inception",
        year: 2010,
        director: "Christopher Nolan",
        duration: "2h 28min",
        actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    },
    {
        title: "The Matrix",
        year: 1999,
        director: "Lana Wachowski, Lilly Wachowski",
        duration: "2h 16min",
        actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    },
    {
        title: "Goodfellas",
        year: 1990,
        director: "Martin Scorsese",
        duration: "2h 26min",
        actors: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        year: 2001,
        director: "Peter Jackson",
        duration: "2h 58min",
        actors: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    },
    {
        title: "Schindler's List",
        year: 1993,
        director: "Steven Spielberg",
        duration: "3h 15min",
        actors: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
    },
    {
        title: "The Silence of the Lambs",
        year: 1991,
        director: "Jonathan Demme",
        duration: "1h 58min",
        actors: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
    },
    {
        title: "Interstellar",
        year: 2014,
        director: "Christopher Nolan",
        duration: "2h 49min",
        actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    },
    {
        title: "Seven",
        year: 1995,
        director: "David Fincher",
        duration: "2h 7min",
        actors: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow"],
    },
    {
        title: "The Departed",
        year: 2006,
        director: "Martin Scorsese",
        duration: "2h 31min",
        actors: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
    },
    {
        title: "Whiplash",
        year: 2014,
        director: "Damien Chazelle",
        duration: "1h 47min",
        actors: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
    },
    {
        title: "The Prestige",
        year: 2006,
        director: "Christopher Nolan",
        duration: "2h 10min",
        actors: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"],
    },
    {
        title: "Gone Girl",
        year: 2014,
        director: "David Fincher",
        duration: "2h 29min",
        actors: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris"],
    },
    {
        title: "Inglourious Basterds",
        year: 2009,
        director: "Quentin Tarantino",
        duration: "2h 33min",
        actors: ["Brad Pitt", "Diane Kruger", "Eli Roth"],
    },
    {
        title: "The Notebook",
        year: 2004,
        director: "Nick Cassavetes",
        duration: "2h 3min",
        actors: ["Ryan Gosling", "Rachel McAdams", "James Garner"],
    }
];
